create database test;

USE TEST;

CREATE TABLE CUSTOMER
(
 ID INT(8) PRIMARY KEY,
 NAME VARCHAR(50) ,
 AGE INT,
 CITY CHAR(50),
 SALARY NUMERIC
);

SELECT * FROM CUSTOMER

DESC CUSTOMER;

INSERT INTO CUSTOMER
VALUE(1,"RAM",20,"MUMBAI",20000),
(2,"SHAM",24,"MUMBAI",30000),
(3,"RAGHAV",21,"MUMBAI",40000),
(4,"RAMESH",22,"MUMBAI",60000),
(5,"ADARSH",22,"MUMBAI",90000);

SELECT * FROM CUSTOMER

UPDATE CUSTOMER  -- UPDATE DATA IN TABLE
SET NAME = "SAGAR"
WHERE ID = 3;

DELETE FROM CUSTOMER -- DELETE SPECIFIC DATA COLUMN FROM TABLE
WHERE ID = 4;

ALTER TABLE CUSTOMER -- ADD NEW COLUMM IN TABLE
ADD COLUMN EMAIL VARCHAR(50);

ALTER TABLE CUSTOMER -- DELETE EMAIL COLUMN
DROP COLUMN EMAIL;

DESC CUSTOMER;

DROP TABLE CUSTOMER: -- DELETEE TABLE FROM DATABASE

TRUNCATE TABLE CUSTOMER; -- DELETE TABLE DATA IN CUSTOMER TABLE NOT A DELETE TABLE

SELECT * FROM CUSTOMER;
SELECT NAME,AGE FROM CUSTOMER;

SELECT NAME FROM CUSTOMER
WHERE SALARY = 20000;

